### ISSUE TITLE
"yarn build" command throws an error - Node Sass does not yet support your current environment

### ISSUE THREAD

**Issue by amnkhan** [WorkshopCLI/workshop-advanced-gulp#34]
Looks like the node-sass no longer supports the latest node versions. When I try to run the `yarn build` command, I am getting the following error:

`
Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/home/devstro/shopify-theme-development/sam_shopify/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/home/devstro/shopify-theme-development/sam_shopify/node_modules/node-sass/lib/index.js:14:35)
`
Screenshot of the error: https://prnt.sc/v-nlJaLSdXGY

**Comment by salexzee** [comment]
Hey. This project is basically dead. Since this was originally built Shopify came out with Online Store 2.0 which requires a completely different way of working with and managing your theme codebase. I'd recommend having a look at some other options Shopify theme dev workflows and toolkits.
